name: Falkor CI - Manual

on:
  workflow_dispatch:
    inputs:
      cli:
        description: Custom CLI arguments for build
        required: false
        default: --release

jobs:
  CIm:
    name: Manual CI Suite

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v2

      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install Npm Dependencies
        run: |-
          npm ci --ignore-scripts

      # - name: Install Npm Peer Dependencies (for npm v6)
      #   if: ${{ matrix.node-version == '14.x' }}
      #   run: |-
      #     npm install typescript@4.4.4 --no-save

      - name: List Packages Installed
        continue-on-error: true
        run: |-
          npm ls --all

      - name: Lint Project
        run: |-
          npm run lint

      - name: Bundle Custom Project
        run: |-
          npx --no-install falkor-bundler ${{ github.event.inputs.cli }} --input src/index.ts

      - name: Build Documentation
        run: |-
          npm run doc
