name: Falkor CI - Develop

on:
  workflow_dispatch:
  schedule:
    - cron: "40 3 * * *" # 3:40am UTC
  pull_request:
    branches:
      - develop

jobs:
  CId:
    name: Develop CI Suite

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    runs-on: ubuntu-latest

    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v2

      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install Npm Dependencies
        run: |-
          npm ci --ignore-scripts

      - name: Install Npm Peer Dependencies (for npm v6)
        if: ${{ matrix.node-version == '14.x' }}
        run: |-
          npm install typescript@4.4.4 --no-save

      - name: Lint Project
        run: |-
          npm run lint

      - name: Bundle Project
        run: |-
          npm run release

      - name: Build Documentation
        run: |-
          npm run doc
