name: Falkor CI - Develop

on:
  workflow_dispatch:
  schedule:
    - cron: "40 3 * * *" # 3:40am UTC
  pull_request:
    branches:
      - develop

jobs:
  CId:
    name: Develop CI Suite

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    runs-on: ubuntu-latest

    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v3

      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # NOTE: since the monorepo setup separate projects do not use npm cache
          # cache: npm

      - name: Install Npm Dependencies
        run: |-
          npm install --ignore-scripts --fund false

      - name: Lint Project
        run: |-
          npm run lint

      - name: Bundle Project
        run: |-
          npm run release

      - name: Build Documentation
        run: |-
          npm run doc
